[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install --include=dev",
  "npm install --workspace=web"
]

[phases.build]
cmds = ["npm run build --workspace=web"]

[start]
cmd = "cd web && NODE_ENV=production node server.js"
