[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm ci --include=optional --legacy-peer-deps"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "cd web && NODE_ENV=production node server.js"
