[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install --include=optional --prefer-offline --no-audit"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "cd web && NODE_ENV=production node server.js"
